# Generated by Django 4.0.4 on 2022-05-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lectorxs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lectorxs', models.CharField(max_length=50)),
                ('pass_lectorxs', models.CharField(max_length=50)),
                ('dni_lectorxs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('titulo', models.CharField(max_length=140)),
                ('bajada', models.TextField()),
                ('periodistxs', models.CharField(max_length=50)),
                ('email_preiodistxs', models.EmailField(max_length=254)),
                ('publicado', models.BooleanField()),
                ('home', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Periodistxs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_periodistxs', models.CharField(max_length=50)),
                ('pass_periodistxs', models.CharField(max_length=50)),
                ('dni_periodistxs', models.IntegerField()),
            ],
        ),
    ]
