# Generated by Django 4.0.4 on 2022-05-31 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodistxs',
            name='leg_periodistxs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
