# Generated by Django 4.0.4 on 2022-05-31 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='fecha',
        ),
    ]
