# Generated by Django 4.0.4 on 2022-05-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_noticia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='bajada',
            field=models.CharField(max_length=100000),
        ),
    ]
