# Generated by Django 4.0.4 on 2022-06-01 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_periodistxs_leg_periodistxs'),
        ('portal', '0003_alter_noticia_bajada'),
    ]

    operations = [
    ]
