# Generated by Django 4.0.4 on 2022-06-01 01:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_merge_20220531_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodistxs',
            name='leg_periodistxs',
        ),
        migrations.AddField(
            model_name='lectorxs',
            name='email_lectorxs',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodistxs',
            name='email_periodistxs',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
