# Generated by Django 4.0.4 on 2022-06-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_delete_lectorxs_delete_periodistxs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lectorxs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lectorxs', models.CharField(max_length=50)),
                ('pass_lectorxs', models.CharField(max_length=50)),
                ('email_lectorxs', models.EmailField(max_length=254)),
                ('dni_lectorxs', models.IntegerField()),
                ('nro_tarjeta_crédito', models.IntegerField()),
                ('modo_suscripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Periodistxs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_periodistxs', models.CharField(max_length=50)),
                ('sigla_periodistxs', models.CharField(max_length=10)),
                ('pass_periodistxs', models.CharField(max_length=50)),
                ('email_periodistxs', models.EmailField(max_length=254)),
                ('dni_periodistxs', models.IntegerField()),
            ],
        ),
    ]
