# Generated by Django 4.0.4 on 2022-06-19 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_post', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='periodistxs',
            new_name='nombre_user',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='email_preiodistxs',
        ),
        migrations.AddField(
            model_name='noticia',
            name='cuerpo',
            field=models.CharField(default=django.utils.timezone.now, max_length=30000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='id_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='bajada',
            field=models.CharField(max_length=10000),
        ),
    ]
